# These are supported funding model platforms

github: [RonSijm, qdot]
ko_fi: RonSijm
custom: ['eth/0xEc4AB6855b2A58F27448c9Bb40E778e4D238FEe2','https://www.paypal.com/donate/?business=CMUF5X42HP22A']